# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: development
  rinkeby:
    host: https://rinkeby.infura.io/v3/e9d700e365b749e5a3bb4548d4b78d61
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01be23585060835e02b77ef475b0cc51aa1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
    oracle: '0x7AFe1118Ea78C1eae84ca8feE5C65Bc76CcF879e'
    jobId: '6d1bfe27e7034b1d87b5270556b17277'
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
wallets:
  from_key: '04191958e9cc56c37c3b467bbd673ced0a79874e4a84f322535c21b2e7e5e70f'
  from_mnemonic: ${MNEMONIC}
  WEB3_INFURA_PROJECT_ID': 'e9d700e365b749e5a3bb4548d4b78d61'